(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import String.


(* NotImplementedYet *)

Definition main (_ : unit) : unit :=
  let _ := v__print (impl_2__new_const (["Smpl
"%string])) in
  let _ := tt in
  tt.
